language: ruby
dist: xenial
services:
  - postgresql
before_install:
  - gem install rubygems-update && update_rubygems
  - yes | rvm @global do gem install bundler -v 1.17.3 || true
cache:
  bundler: true
  directories:
    - node_modules
before_script:
  - bundle install
  - cp lib/database_jenkins.yml config/database.yml
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:schema:load
  - RAILS_ENV=test bundle exec rails s -d
  - RAILS_ENV=test bundle exec rspec
  - kill `cat tmp/pids/server.pid`

